#!/usr/bin/env python

import sys

from gl import Gitlab

if __name__ == '__main__':

    if len(sys.argv) != 2:
        print 'Usage: Copy new project in Tera Group'
        print '     ' + sys.argv[0] + ' <group id> <project name>'
        print
        print 'Get group id from show_all_groups'
        sys.exit()

    project_id = sys.argv[1]
    name = sys.argv[2]
    
    new_gl = Gitlab()
    new_gl.get_project_manager()
    
    data = {'name': name, 'namespace_id': project_id}
    new_gl.pm.create(data)
    print 'project {} created in group {}'.format(name, 'Tera')
